# Generated by Django 5.1.2 on 2024-10-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_text', models.CharField(max_length=200)),
                ('user_creator', models.CharField(max_length=16)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]