# Generated by Django 4.2.16 on 2024-10-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_text', models.CharField(blank=True, max_length=200, null=True)),
                ('user_creator', models.CharField(max_length=16)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('description', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=7)),
                ('category', models.CharField(blank=True, choices=[('RENDIMIENTO', 'Rendimiento'), ('UI', 'UI'), ('DOCUMENTACION', 'Documentación'), ('APIS', 'API’s'), ('BASEDATOS', 'Bases de datos'), ('SEGURIDAD', 'Seguridad'), ('DEPENDENCIAS', 'Dependencias de terceros')], max_length=20, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
