# Generated by Django 4.2.16 on 2024-11-04 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.CharField(blank=True, choices=[('RENDIMIENTO', 'Rendimiento'), ('UI', 'UI'), ('DOCUMENTACION', 'Documentación'), ('APIS', 'API’s'), ('BASEDATOS', 'Bases de datos'), ('SEGURIDAD', 'Seguridad'), ('DEPENDENCIAS', 'Dependencias de terceros'), ('REFACTORIZACIÓN', 'Refactorización')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='incident',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AddField(
            model_name='incident',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='organizaciones.organizacion'),
        ),
        migrations.AddField(
            model_name='incident',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=7),
        ),
        migrations.AddField(
            model_name='incident',
            name='related_incidents',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='user_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
