# Generated by Django 4.2.5 on 2024-10-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
