# Generated by Django 5.1.2 on 2024-11-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('en_progreso', 'En progreso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado'), ('rechazado', 'Rechazado')], default='nuevo', max_length=20),
        ),
    ]
