# Generated by Django 4.2.5 on 2024-10-15 19:53

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
