# Generated by Django 4.2.5 on 2024-10-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incident_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
