# Generated by Django 5.1.2 on 2024-11-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incident_incident_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_text',
            field=models.CharField(default='nombre', max_length=200),
        ),
    ]
