# Generated by Django 5.1.2 on 2024-10-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incidenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='user_creator',
            field=models.CharField(editable=False, max_length=16),
        ),
    ]
