# Generated by Django 4.2.5 on 2024-10-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_alter_incident_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
