# Generated by Django 4.2.16 on 2024-10-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=7),
        ),
    ]
