# Generated by Django 4.2.5 on 2024-11-16 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0001_initial'),
        ('incidents', '0006_incident_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to='organizaciones.miembroorganizacion'),
        ),
    ]
