# Generated by Django 5.1.2 on 2024-10-30 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_remove_incident_organizacion'),
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='organizaciones.organizacion'),
        ),
    ]
